---
format: 
  html:
    page-layout: full
---

<script src="typed_js/typed.min.js"></script>
<script src="//cdn.wordart.com/wordart.min.js" async defer></script>

<style>
  body {

  background-color: #white;
  background-size: auto;
  background-repeat: no-repeat;
}

.container {
  display: flex;
  justify-content: space-between;
}

.left-side,
.right-side {
  width: 40%;
  display: flex;
  align-items: center;
  justify-content: center;
}

.right-side {
  width: 60%;
}

.center-xy {

    position: absolute;
    top: 40%;
    margin:10px;
    width: auto ;
    max-width:auto;
  }

  .center-xy-for-name {
    position: absolute;
    top: 40%;
    left: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    text-align: right;
    flex-direction: column;

  }

  @media (max-width: 768px) {
    .center-xy {
      position: fixed;
      bottom: 0;
      left: 0;
      width: 100%;
      max-width: 100%;
      height: 50%;
    }

    .center-xy-for-name {
      position: absolute;
      top: 30%;
      right: 0;
      text-align: right;
    }
  }
  .wordart-container {
    position: relative;
    width:400px;
    height: 400px;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;

}

  .wordart-element {
    position: absolute;
    top: 0;
    left: 0;
    opacity: 0;
    transition: opacity 0.5s ease-in-out;
  }

  .wordart-element.active {
    opacity: 1;
}
</style>

::: {.container)

::: {.right-side}
<div class="center-xy">
<div class="wordart-container">
  <div class="wordart-element" data-wordart-src="//cdn.wordart.com/json/mg08pcakpaxf"></div>
  <div class="wordart-element" style="top: 0; left: 0; z-index: -1;" data-wordart-src="//cdn.wordart.com/json/kwhupk8pmfuv"></div>
  <div class="wordart-element" style="top: 0; left: 0; z-index: -2;" data-wordart-src="//cdn.wordart.com/json/r5jlzel91jxv"></div>
  <div class="wordart-element" style="top: 0; left: 0; z-index: -3;" data-wordart-src="//cdn.wordart.com/json/pcxs6f96tfrn"></div>
  <div class="wordart-element" style="top: 0; left: 0; z-index: -4;" data-wordart-src="//cdn.wordart.com/json/6946xgf3vmnq"  ></div>
</div>
</div>
:::

:::{.left-side}
:::: {.center-xy-for-name}
# I am Rishikesavan Ramesh.
  <span class="typing"></span>
::::

:::

:::

<script type="text/javascript">
  var typed = new Typed('.typing', {
    strings: [ "Linux User.", "Coder.", "Foss Advocate.","Designer.", "Mechatronics Engineer."],
    loop: true,
    typeSpeed: 65,
    backSpeed: 65,
    smartBackspace: false,
    shuffle: false,
    startDelay: 1000,
    loopCount: Infinity,
    showCursor: true,
    cursorChar: '|',
    onComplete: function(self) {
      self.cursor.remove();
    },
    preStringTyped: function(arrayPos) {
      var wordartElements = document.querySelectorAll('.wordart-element');
      var currentIndex = arrayPos % wordartElements.length;

      for (var i = 0; i < wordartElements.length; i++) {
        wordartElements[i].classList.remove('active');
      }

      wordartElements[currentIndex].classList.add('active');
    }
  });

  </script>


